name: test-pipeline

env:
  APP_ENV: test

steps:
  - name: print env
    run: echo "Running on branch $BUILDNOW_BRANCH, commit $BUILDNOW_COMMIT"

  - name: plugin test
    plugin: net.colourlabs.test@latest
    with:
      name: "test! works?"

  - name: check workspace
    run: ls -la $BUILDNOW_WORKSPACE